### ISSUE TITLE
Support for macOS Mojave (10.14)

### ISSUE THREAD

**Issue by joachimesque** [rhaining/zooooom-screensaver#1]
The screensaver can't be installed on macOS Mojave (10.14). Is there a plan to make it compatible?

**Comment by rhaining** [comment]
hey @joachimesque!  i wrote a lot of the UI in SwiftUI, which is only compatible with macOS 10.15+. at some point, i might go back and rewrite it so it's compatible with previous macOS versions… but i don't have immediate plans to.

**Comment by joachimesque** [comment]
Thanks for your answer! Don't worry about Mojave compatibility, I know I should update my mac :)
